#!/bin/sh

CONV="perl -W $HERE/../to-readme.pl"
CONV_SAMPLE1="$CONV <$HERE/samples/sample1.roff"

conv_sample1 () {
	$CONV "$@" < "$HERE/samples/sample1.roff"
}
conv_sample1_headlines () {
	$CONV "$@" < "$HERE/samples/sample1.roff" | grep '^#'
}


DEFAULT_COMMENT="autogenerated"

TESTPROG_NAME="testprog"
TESTPROG_SECTION="7"
TESTPROG_SHORTNAME="TESTPROG"
TESTPROG_VERSION="0.9.2"
TESTPROG_DATE="April 2017"

