.TH "A<B>" "7" "July 2017" "a<b> 0.9.2" ""
.SH NAME
a<b> - checks if a < b or not.
.SH SYNOPSIS
Call syntax: \fBa<b>\fR \fIinput\fR [\fIoutput\fR]
.SH MAIN A<B> DESCRIPTION
This text describes the mysterious \(lqa<b>\(rq program.
.P
.nf
This is an unformatted code block.

It, too, is about the a<b> program.
.fi
.P
.B Now we have a bold line about a<b>!
.P
