.TH TESTPROG "7" "January 2020" "testprog 0.9.2" ""
.SH JUST A REGULAR CODE BLOCK
.\" PLAIN
There's a text line between the marker and the .nf block, so nothing special should happen.
.P
.nf
this is the code block
  indented x2
.fi
.P
This is \fBregular\fR text again.
.SH PREFORMATTED BLOCK
.\" PLAIN
.nf
This is the preformatted
block.
   indented x3
.fi
.P
This is \fBregular\fR text again.
