.TH TESTPROG "7" "April 2017" "testprog 0.9.2" ""
.SH NAME
othername \- does stuff, mostly
.SH SYNOPSIS
\fBtestprog\fR
[\fIOPTIONS\fR]
[\fB\-\-\fR]
[\fIFILENAME\fR...]
.SH DESCRIPTION
This program does stuff to its input files.
.P
It's very similar to the \fBfrobnicator\fR(1).
.SH OPTIONS
This sections explains available program options.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show more details of the internal transconfrobnication process.
.TP
.B \-q, \-\-quiet
No output, only an exit code.
.TP
\fB\-m\fR \fIN\fR, \fB\fB\-\-mode\fR \fIMODE\fR
Chooses a different operating mode.
The default mode is \fBM0\fR.
Possible modes:
.PD 0
.RS
.IP - 2
.BR M0 :
Level zero mode.
This is the default.
.IP - 2
.BR M1 :
Level one mode.
.IP - 2
.BR M2 :
Level two mode.
Use with caution!
.RE
.PD
.P
This is the section end.
.SH SPECIAL CHARACTERS
dq<\(dq>
lq<\(lq>
rq<\(rq>
nbsp\ eol.
.SS Texty Subsection
This is a subsection
with content.
.SH HIGHLIGHTING
0 \fBinline bold\fR 0 \fIinline italics\fR 0
.P
1
.B "bold"
1
.I italics "iii1" iii2
1
.P
.BR bold    " 2 "    "bold"    " 2"
.P
.RB "3 " "bold" \ 3\  bold " 3"
.P
.BR aaa\ bbb\ ccc " normal " bold"quoted \  spaced"bold " normal2"
.P
.BI "bold-4 " "italics-4 " bold4 " italics4"
.SH BREAKS
line 1
line 2
.br
line 3
.P
line 4
.SH A SIMPLE APPROACH TO TITLE-CASING OF KNOWN WORDS LIKE XML AND CRAZYCAPS
This section is only there for its title.
