.TH TESTPROG "7" "December 2019" "testprog 0.9.2" ""
.SH DESCRIPTION
This is the program's main description.
If you want the minutiae,
check out the section below:
.\" LINK-TO MORE DETAILS, INCLUDING NUMB3RS AND SPECIAL CHÁRACTÈRß
\(lqMore Details (…)\(rq.
.SH MORE DETAILS, INCLUDING NUMB3RS AND SPECIAL CHÁRACTÈRß
Lots of boring stuff, really.
Head back to the
.\" LINK-TO DESCRIPTION
\fIDescription\fR section
if this is too much.
.SH TRAILING PUNCTUATION
This is
.\" LINK-TO DESCRIPTION
a link.
.SH INDENTED SECTION
.TP
.B Subject 1
This is an
.\" LINK-TO DESCRIPTION
indented link.
This is indented text.
