.TH HX "1" "July 2019" "hx 0.13.0" ""
.SH OUTPUT
\fBhx\fR makes extensive use of ANSI coloring sequences,
including the \(lq\fBCSI\ 38;5;\fR\fIn\fR\ \fBm\fR\(rq sequence
for extended color selection
and the \(lq\fBCSI\ 38;2;\fR\fIr\fR\fB;\fR\fIg\fR\fB;\fR\fIb\fR\ \fBm\fR\(rq sequence
for RGB true-color selection.
