.TH TESTPROG "7" "July 2017" "testprog 0.9.2" ""
.SH TEXT BLOCK
This section contains regular text.
.P
But after a while,
well-formatted URLs
(https://en.wikipedia.org/wiki/URL)
show up!
.P
They may also end a
sentence
(https://en.wiktionary.org/wiki/sentence).
.P
This URL is not in parentheses,
so it should not be its own link title
in the output:
https://en.wikipedia.org/wiki/URL
(plain url)
.P
For more information, see
.\"   INTERNAL-LINK   
<doc/More_Information.md>.
.P
This can also be done with a different
.\" INTERNAL-LINK
link title
<doc/More_Information.md>!
.P
Internal link followed by an angle bracket:
.\"   INTERNAL-LINK   
<doc/More_Information.md>
<other stuff>
.P
Fin!
.SH AUTHOR
At least in this section, e-mail addresses
should automatically get converted to a link:
author@dummy.test
This should also work inside angle brackets:
<author2@dummy.test>
Fin!
